# Generated by Django 4.0.5 on 2022-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300)),
                ('institute_name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
